[package]
name = "assuan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1"
zeroize = "1"

[dev-dependencies]
rand = "0.8"
rand_dev = "0.1"
