$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: '0.2'

dictionaryDefinitions:
  - name: project-words
    path: './dictionary/project-words.txt'
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - '/target'
  - '/assuan-server/src/error_code.rs'
