use core::fmt;

/// Error that has an error code assigned to it
pub trait HasErrorCode {
    /// Error code
    fn code(&self) -> ErrorCode;
}

impl HasErrorCode for core::convert::Infallible {
    fn code(&self) -> ErrorCode {
        match *self {}
    }
}

/// Wraps an error and assigns an error code to it
pub struct WithErrorCode<E> {
    /// Error code assigned to the error
    pub code: ErrorCode,
    /// The error
    pub error: E,
}

impl<E> HasErrorCode for WithErrorCode<E> {
    fn code(&self) -> ErrorCode {
        self.code
    }
}

impl<E: fmt::Display> fmt::Display for WithErrorCode<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.error.fmt(f)
    }
}

macro_rules! define_error_code {
    ($($code:literal $name:ident $comment_line:expr),+$(,)*) => {
        /// Error code defined by GPG library
        ///
        /// List of error codes was taken from here: <https://github.com/gpg/libgpg-error/blob/4a9def77488f2631f71737357d9e9dd874c9b302/src/err-codes.h.in>
        #[derive(Debug, Clone, Copy)]
        pub struct ErrorCode(pub u32);

        impl ErrorCode {$(
            #[doc = $comment_line]
            pub const $name: Self = Self($code);
        )+}
    };
}

define_error_code! {
    0	NO_ERROR		"Success",
    1	GENERAL			"General error",
    2	UNKNOWN_PACKET		"Unknown packet",
    3	UNKNOWN_VERSION		"Unknown version in packet",
    4	PUBKEY_ALGO		"Invalid public key algorithm",
    5	DIGEST_ALGO		"Invalid digest algorithm",
    6	BAD_PUBKEY		"Bad public key",
    7	BAD_SECKEY		"Bad secret key",
    8	BAD_SIGNATURE		"Bad signature",
    9	NO_PUBKEY		"No public key",
    10	CHECKSUM		"Checksum error",
    11	BAD_PASSPHRASE		"Bad passphrase",
    12	CIPHER_ALGO		"Invalid cipher algorithm",
    13	KEYRING_OPEN		"Cannot open keyring",
    14	INV_PACKET		"Invalid packet",
    15	INV_ARMOR		"Invalid armor",
    16	NO_USER_ID		"No user ID",
    17	NO_SECKEY		"No secret key",
    18	WRONG_SECKEY		"Wrong secret key used",
    19	BAD_KEY			"Bad session key",
    20	COMPR_ALGO		"Unknown compression algorithm",
    21	NO_PRIME		"Number is not prime",
    22	NO_ENCODING_METHOD	"Invalid encoding method",
    23	NO_ENCRYPTION_SCHEME	"Invalid encryption scheme",
    24	NO_SIGNATURE_SCHEME	"Invalid signature scheme",
    25	INV_ATTR		"Invalid attribute",
    26	NO_VALUE		"No value",
    27	NOT_FOUND		"Not found",
    28	VALUE_NOT_FOUND		"Value not found",
    29	SYNTAX			"Syntax error",
    30	BAD_MPI			"Bad MPI value",
    31	INV_PASSPHRASE		"Invalid passphrase",
    32	SIG_CLASS		"Invalid signature class",
    33	RESOURCE_LIMIT		"Resources exhausted",
    34	INV_KEYRING		"Invalid keyring",
    35	TRUSTDB			"Trust DB error",
    36	BAD_CERT		"Bad certificate",
    37	INV_USER_ID		"Invalid user ID",
    38	UNEXPECTED		"Unexpected error",
    39	TIME_CONFLICT		"Time conflict",
    40	KEYSERVER		"Keyserver error",
    41	WRONG_PUBKEY_ALGO	"Wrong public key algorithm",
    42	TRIBUTE_TO_D_A		"Tribute to D. A.",
    43	WEAK_KEY		"Weak encryption key",
    44	INV_KEYLEN		"Invalid key length",
    45	INV_ARG			"Invalid argument",
    46	BAD_URI			"Syntax error in URI",
    47	INV_URI			"Invalid URI",
    48	NETWORK			"Network error",
    49	UNKNOWN_HOST		"Unknown host",
    50	SELFTEST_FAILED		"Selftest failed",
    51	NOT_ENCRYPTED		"Data not encrypted",
    52	NOT_PROCESSED		"Data not processed",
    53	UNUSABLE_PUBKEY		"Unusable public key",
    54	UNUSABLE_SECKEY		"Unusable secret key",
    55	INV_VALUE		"Invalid value",
    56	BAD_CERT_CHAIN		"Bad certificate chain",
    57	MISSING_CERT		"Missing certificate",
    58	NO_DATA			"No data",
    59	BUG			"Bug",
    60	NOT_SUPPORTED		"Not supported",
    61	INV_OP			"Invalid operation code",
    62	TIMEOUT			"Timeout",
    63	INTERNAL		"Internal error",
    64	EOF_GCRYPT		"EOF (gcrypt)",
    65	INV_OBJ			"Invalid object",
    66	TOO_SHORT		"Provided object is too short",
    67	TOO_LARGE		"Provided object is too large",
    68	NO_OBJ			"Missing item in object",
    69	NOT_IMPLEMENTED		"Not implemented",
    70	CONFLICT		"Conflicting use",
    71	INV_CIPHER_MODE		"Invalid cipher mode",
    72	INV_FLAG		"Invalid flag",
    73	INV_HANDLE		"Invalid handle",
    74	TRUNCATED		"Result truncated",
    75	INCOMPLETE_LINE		"Incomplete line",
    76	INV_RESPONSE		"Invalid response",
    77	NO_AGENT		"No agent running",
    78	AGENT			"Agent error",
    79	INV_DATA		"Invalid data",
    80	ASSUAN_SERVER_FAULT	"Unspecific Assuan server fault",
    81	ASSUAN			"General Assuan error",
    82	INV_SESSION_KEY		"Invalid session key",
    83	INV_SEXP		"Invalid S-expression",
    84	UNSUPPORTED_ALGORITHM	"Unsupported algorithm",
    85	NO_PIN_ENTRY		"No pinentry",
    86	PIN_ENTRY		"pinentry error",
    87	BAD_PIN			"Bad PIN",
    88	INV_NAME		"Invalid name",
    89	BAD_DATA		"Bad data",
    90	INV_PARAMETER		"Invalid parameter",
    91	WRONG_CARD		"Wrong card",
    92	NO_DIRMNGR		"No dirmngr",
    93	DIRMNGR			"dirmngr error",
    94	CERT_REVOKED		"Certificate revoked",
    95	NO_CRL_KNOWN		"No CRL known",
    96	CRL_TOO_OLD		"CRL too old",
    97	LINE_TOO_LONG		"Line too long",
    98	NOT_TRUSTED		"Not trusted",
    99	CANCELED		"Operation cancelled",
    100	BAD_CA_CERT		"Bad CA certificate",
    101	CERT_EXPIRED		"Certificate expired",
    102	CERT_TOO_YOUNG		"Certificate too young",
    103	UNSUPPORTED_CERT	"Unsupported certificate",
    104	UNKNOWN_SEXP		"Unknown S-expression",
    105	UNSUPPORTED_PROTECTION	"Unsupported protection",
    106	CORRUPTED_PROTECTION	"Corrupted protection",
    107	AMBIGUOUS_NAME		"Ambiguous name",
    108	CARD			"Card error",
    109	CARD_RESET		"Card reset required",
    110	CARD_REMOVED		"Card removed",
    111	INV_CARD		"Invalid card",
    112	CARD_NOT_PRESENT	"Card not present",
    113	NO_PKCS15_APP		"No PKCS15 application",
    114	NOT_CONFIRMED		"Not confirmed",
    115	CONFIGURATION		"Configuration error",
    116	NO_POLICY_MATCH		"No policy match",
    117	INV_INDEX		"Invalid index",
    118	INV_ID			"Invalid ID",
    119	NO_SCDAEMON		"No SmartCard daemon",
    120	SCDAEMON		"SmartCard daemon error",
    121	UNSUPPORTED_PROTOCOL	"Unsupported protocol",
    122	BAD_PIN_METHOD		"Bad PIN method",
    123	CARD_NOT_INITIALIZED	"Card not initialized",
    124	UNSUPPORTED_OPERATION	"Unsupported operation",
    125	WRONG_KEY_USAGE		"Wrong key usage",
    126	NOTHING_FOUND		"Nothing found",
    127	WRONG_BLOB_TYPE		"Wrong blob type",
    128	MISSING_VALUE		"Missing value",
    129	HARDWARE		"Hardware problem",
    130	PIN_BLOCKED		"PIN blocked",
    131	USE_CONDITIONS		"Conditions of use not satisfied",
    132	PIN_NOT_SYNCED		"PINs are not synced",
    133	INV_CRL			"Invalid CRL",
    134	BAD_BER			"BER error",
    135	INV_BER			"Invalid BER",
    136	ELEMENT_NOT_FOUND	"Element not found",
    137	IDENTIFIER_NOT_FOUND	"Identifier not found",
    138	INV_TAG			"Invalid tag",
    139	INV_LENGTH		"Invalid length",
    140	INV_KEYINFO		"Invalid key info",
    141	UNEXPECTED_TAG		"Unexpected tag",
    142	NOT_DER_ENCODED		"Not DER encoded",
    143	NO_CMS_OBJ		"No CMS object",
    144	INV_CMS_OBJ		"Invalid CMS object",
    145	UNKNOWN_CMS_OBJ		"Unknown CMS object",
    146	UNSUPPORTED_CMS_OBJ	"Unsupported CMS object",
    147	UNSUPPORTED_ENCODING	"Unsupported encoding",
    148	UNSUPPORTED_CMS_VERSION	"Unsupported CMS version",
    149	UNKNOWN_ALGORITHM	"Unknown algorithm",
    150	INV_ENGINE		"Invalid crypto engine",
    151	PUBKEY_NOT_TRUSTED	"Public key not trusted",
    152	DECRYPT_FAILED		"Decryption failed",
    153	KEY_EXPIRED		"Key expired",
    154	SIG_EXPIRED		"Signature expired",
    155	ENCODING_PROBLEM	"Encoding problem",
    156	INV_STATE		"Invalid state",
    157	DUP_VALUE		"Duplicated value",
    158	MISSING_ACTION		"Missing action",
    159	MODULE_NOT_FOUND	"ASN.1 module not found",
    160	INV_OID_STRING		"Invalid OID string",
    161	INV_TIME		"Invalid time",
    162	INV_CRL_OBJ		"Invalid CRL object",
    163	UNSUPPORTED_CRL_VERSION	"Unsupported CRL version",
    164	INV_CERT_OBJ		"Invalid certificate object",
    165	UNKNOWN_NAME		"Unknown name",
    166	LOCALE_PROBLEM		"A locale function failed",
    167	NOT_LOCKED		"Not locked",
    168	PROTOCOL_VIOLATION	"Protocol violation",
    169	INV_MAC			"Invalid MAC",
    170	INV_REQUEST		"Invalid request",
    171	UNKNOWN_EXTN		"Unknown extension",
    172	UNKNOWN_CRIT_EXTN	"Unknown critical extension",
    173	LOCKED			"Locked",
    174	UNKNOWN_OPTION		"Unknown option",
    175	UNKNOWN_COMMAND		"Unknown command",
    176	NOT_OPERATIONAL		"Not operational",
    177	NO_PASSPHRASE		"No passphrase given",
    178	NO_PIN			"No PIN given",
    179	NOT_ENABLED		"Not enabled",
    180	NO_ENGINE		"No crypto engine",
    181	MISSING_KEY		"Missing key",
    182	TOO_MANY		"Too many objects",
    183	LIMIT_REACHED		"Limit reached",
    184	NOT_INITIALIZED		"Not initialized",
    185	MISSING_ISSUER_CERT	"Missing issuer certificate",
    186	NO_KEYSERVER		"No keyserver available",
    187	INV_CURVE		"Invalid elliptic curve",
    188	UNKNOWN_CURVE		"Unknown elliptic curve",
    189	DUP_KEY			"Duplicated key",
    190	AMBIGUOUS		"Ambiguous result",
    191	NO_CRYPT_CTX		"No crypto context",
    192	WRONG_CRYPT_CTX		"Wrong crypto context",
    193	BAD_CRYPT_CTX		"Bad crypto context",
    194	CRYPT_CTX_CONFLICT	"Conflict in the crypto context",
    195	BROKEN_PUBKEY		"Broken public key",
    196	BROKEN_SECKEY		"Broken secret key",
    197	MAC_ALGO		"Invalid MAC algorithm",
    198	FULLY_CANCELED		"Operation fully cancelled",
    199	UNFINISHED		"Operation not yet finished",
    200	BUFFER_TOO_SHORT	"Buffer too short",
    201	SEXP_INV_LEN_SPEC	"Invalid length specifier in S-expression",
    202	SEXP_STRING_TOO_LONG	"String too long in S-expression",
    203	SEXP_UNMATCHED_PAREN	"Unmatched parentheses in S-expression",
    204	SEXP_NOT_CANONICAL	"S-expression not canonical",
    205	SEXP_BAD_CHARACTER	"Bad character in S-expression",
    206	SEXP_BAD_QUOTATION	"Bad quotation in S-expression",
    207	SEXP_ZERO_PREFIX	"Zero prefix in S-expression",
    208	SEXP_NESTED_DH		"Nested display hints in S-expression",
    209	SEXP_UNMATCHED_DH	"Unmatched display hints",
    210	SEXP_UNEXPECTED_PUNC	"Unexpected reserved punctuation in S-expression",
    211	SEXP_BAD_HEX_CHAR	"Bad hexadecimal character in S-expression",
    212	SEXP_ODD_HEX_NUMBERS	"Odd hexadecimal numbers in S-expression",
    213	SEXP_BAD_OCT_CHAR	"Bad octal character in S-expression",
    217	SUBKEYS_EXP_OR_REV	"All subkeys are expired or revoked",
    218	DB_CORRUPTED		"Database is corrupted",
    219	SERVER_FAILED		"Server indicated a failure",
    220	NO_NAME			"No name",
    221	NO_KEY			"No key",
    222	LEGACY_KEY		"Legacy key",
    223	REQUEST_TOO_SHORT	"Request too short",
    224	REQUEST_TOO_LONG	"Request too long",
    225	OBJ_TERM_STATE		"Object is in termination state",
    226	NO_CERT_CHAIN		"No certificate chain",
    227	CERT_TOO_LARGE		"Certificate is too large",
    228	INV_RECORD		"Invalid record",
    229	BAD_MAC			"The MAC does not verify",
    230	UNEXPECTED_MSG		"Unexpected message",
    231	COMPR_FAILED		"Compression or decompression failed",
    232	WOULD_WRAP		"A counter would wrap",
    233	FATAL_ALERT		"Fatal alert message received",
    234	NO_CIPHER		"No cipher algorithm",
    235	MISSING_CLIENT_CERT	"Missing client certificate",
    236	CLOSE_NOTIFY		"Close notification received",
    237	TICKET_EXPIRED		"Ticket expired",
    238	BAD_TICKET		"Bad ticket",
    239	UNKNOWN_IDENTITY	"Unknown identity",
    240	BAD_HS_CERT		"Bad certificate message in handshake",
    241	BAD_HS_CERT_REQ		"Bad certificate request message in handshake",
    242	BAD_HS_CERT_VER		"Bad certificate verify message in handshake",
    243	BAD_HS_CHANGE_CIPHER	"Bad change cipher message in handshake",
    244	BAD_HS_CLIENT_HELLO	"Bad client hello message in handshake",
    245	BAD_HS_SERVER_HELLO	"Bad server hello message in handshake",
    246	BAD_HS_SERVER_HELLO_DONE	"Bad server hello done message in handshake",
    247	BAD_HS_FINISHED		"Bad finished message in handshake",
    248	BAD_HS_SERVER_KEX	"Bad server key exchange message in handshake",
    249	BAD_HS_CLIENT_KEX	"Bad client key exchange message in handshake",
    250	BOGUS_STRING		"Bogus string",
    251	FORBIDDEN		"Forbidden",
    252	KEY_DISABLED		"Key disabled",
    253	KEY_ON_CARD		"Not possible with a card based key",
    254	INV_LOCK_OBJ		"Invalid lock object",
    255	TRUE			"True",
    256	FALSE			"False",
    257	ASS_GENERAL		"General IPC error",
    258	ASS_ACCEPT_FAILED	"IPC accept call failed",
    259	ASS_CONNECT_FAILED	"IPC connect call failed",
    260	ASS_INV_RESPONSE	"Invalid IPC response",
    261	ASS_INV_VALUE		"Invalid value passed to IPC",
    262	ASS_INCOMPLETE_LINE	"Incomplete line passed to IPC",
    263	ASS_LINE_TOO_LONG	"Line passed to IPC too long",
    264	ASS_NESTED_COMMANDS	"Nested IPC commands",
    265	ASS_NO_DATA_CB		"No data callback in IPC",
    266	ASS_NO_INQUIRE_CB	"No inquire callback in IPC",
    267	ASS_NOT_A_SERVER	"Not an IPC server",
    268	ASS_NOT_A_CLIENT	"Not an IPC client",
    269	ASS_SERVER_START	"Problem starting IPC server",
    270	ASS_READ_ERROR		"IPC read error",
    271	ASS_WRITE_ERROR		"IPC write error",
    273	ASS_TOO_MUCH_DATA	"Too much data for IPC layer",
    274	ASS_UNEXPECTED_CMD	"Unexpected IPC command",
    275	ASS_UNKNOWN_CMD		"Unknown IPC command",
    276	ASS_SYNTAX		"IPC syntax error",
    277	ASS_CANCELED		"IPC call has been cancelled",
    278	ASS_NO_INPUT		"No input source for IPC",
    279	ASS_NO_OUTPUT		"No output source for IPC",
    280	ASS_PARAMETER		"IPC parameter error",
    281	ASS_UNKNOWN_INQUIRE	"Unknown IPC inquire",
    300	ENGINE_TOO_OLD		"Crypto engine too old",
    301	WINDOW_TOO_SMALL	"Screen or window too small",
    302	WINDOW_TOO_LARGE	"Screen or window too large",
    303	MISSING_ENVVAR		"Required environment variable not set",
    304	USER_ID_EXISTS		"User ID already exists",
    305	NAME_EXISTS		"Name already exists",
    306	DUP_NAME		"Duplicated name",
    307	TOO_YOUNG		"Object is too young",
    308	TOO_OLD			"Object is too old",
    309	UNKNOWN_FLAG		"Unknown flag",
    310	INV_ORDER		"Invalid execution order",
    311	ALREADY_FETCHED		"Already fetched",
    312	TRY_LATER		"Try again later",
    313	WRONG_NAME		"Wrong name",
    314	NO_AUTH			"Not authenticated",
    315	BAD_AUTH		"Bad authentication",
    316	NO_KEYBOXD		"No Keybox daemon running",
    317	KEYBOXD			"Keybox daemon error",
    318	NO_SERVICE		"Service is not running",
    319	SERVICE			"Service error",
    320	BAD_PUK			"Bad PUK",
    321	NO_RESET_CODE		"No reset code",
    322	BAD_RESET_CODE		"Bad reset code",
    666	SYSTEM_BUG		"System bug detected",
    711	DNS_UNKNOWN		"Unknown DNS error",
    712	DNS_SECTION		"Invalid DNS section",
    713	DNS_ADDRESS		"Invalid textual address form",
    714	DNS_NO_QUERY		"Missing DNS query packet",
    715	DNS_NO_ANSWER		"Missing DNS answer packet",
    716	DNS_CLOSED		"Connection closed in DNS",
    717	DNS_VERIFY		"Verification failed in DNS",
    718	DNS_TIMEOUT		"DNS Timeout",
    721	LDAP_GENERAL		"General LDAP error",
    722	LDAP_ATTR_GENERAL	"General LDAP attribute error",
    723	LDAP_NAME_GENERAL	"General LDAP name error",
    724	LDAP_SECURITY_GENERAL	"General LDAP security error",
    725	LDAP_SERVICE_GENERAL	"General LDAP service error",
    726	LDAP_UPDATE_GENERAL	"General LDAP update error",
    727	LDAP_E_GENERAL		"Experimental LDAP error code",
    728	LDAP_X_GENERAL		"Private LDAP error code",
    729	LDAP_OTHER_GENERAL	"Other general LDAP error",
    750	LDAP_X_CONNECTING	"LDAP connecting failed (X)",
    751	LDAP_REFERRAL_LIMIT	"LDAP referral limit exceeded",
    752	LDAP_CLIENT_LOOP	"LDAP client loop",
    754	LDAP_NO_RESULTS		"No LDAP results returned",
    755	LDAP_CONTROL_NOT_FOUND	"LDAP control not found",
    756	LDAP_NOT_SUPPORTED	"Not supported by LDAP",
    757	LDAP_CONNECT		"LDAP connect error",
    758	LDAP_NO_MEMORY		"Out of memory in LDAP",
    759	LDAP_PARAM		"Bad parameter to an LDAP routine",
    760	LDAP_USER_CANCELLED	"User cancelled LDAP operation",
    761	LDAP_FILTER		"Bad LDAP search filter",
    762	LDAP_AUTH_UNKNOWN	"Unknown LDAP authentication method",
    763	LDAP_TIMEOUT		"Timeout in LDAP",
    764	LDAP_DECODING		"LDAP decoding error",
    765	LDAP_ENCODING		"LDAP encoding error",
    766	LDAP_LOCAL		"LDAP local error",
    767	LDAP_SERVER_DOWN	"Cannot contact LDAP server",
    768	LDAP_SUCCESS		"LDAP success",
    769	LDAP_OPERATIONS		"LDAP operations error",
    770	LDAP_PROTOCOL		"LDAP protocol error",
    771	LDAP_TIMELIMIT		"Time limit exceeded in LDAP",
    772	LDAP_SIZELIMIT		"Size limit exceeded in LDAP",
    773	LDAP_COMPARE_FALSE	"LDAP compare false",
    774	LDAP_COMPARE_TRUE	"LDAP compare true",
    775	LDAP_UNSUPPORTED_AUTH	"LDAP authentication method not supported",
    776	LDAP_STRONG_AUTH_RQRD	"Strong(er) LDAP authentication required",
    777	LDAP_PARTIAL_RESULTS	"Partial LDAP results+referral received",
    778	LDAP_REFERRAL		"LDAP referral",
    779	LDAP_ADMINLIMIT		"Administrative LDAP limit exceeded",
    780	LDAP_UNAVAIL_CRIT_EXTN	"Critical LDAP extension is unavailable",
    781	LDAP_CONFIDENT_RQRD	"Confidentiality required by LDAP",
    782	LDAP_SASL_BIND_INPROG	"LDAP SASL bind in progress",
    784	LDAP_NO_SUCH_ATTRIBUTE	"No such LDAP attribute",
    785	LDAP_UNDEFINED_TYPE	"Undefined LDAP attribute type",
    786	LDAP_BAD_MATCHING	"Inappropriate matching in LDAP",
    787	LDAP_CONST_VIOLATION	"Constraint violation in LDAP",
    788	LDAP_TYPE_VALUE_EXISTS	"LDAP type or value exists",
    789	LDAP_INV_SYNTAX		"Invalid syntax in LDAP",
    800	LDAP_NO_SUCH_OBJ	"No such LDAP object",
    801	LDAP_ALIAS_PROBLEM	"LDAP alias problem",
    802	LDAP_INV_DN_SYNTAX	"Invalid DN syntax in LDAP",
    803	LDAP_IS_LEAF		"LDAP entry is a leaf",
    804	LDAP_ALIAS_DEREF	"LDAP alias dereferencing problem",
    815	LDAP_X_PROXY_AUTH_FAIL	"LDAP proxy authorization failure (X)",
    816	LDAP_BAD_AUTH		"Inappropriate LDAP authentication",
    817	LDAP_INV_CREDENTIALS	"Invalid LDAP credentials",
    818	LDAP_INSUFFICIENT_ACC	"Insufficient access for LDAP",
    819	LDAP_BUSY		"LDAP server is busy",
    820	LDAP_UNAVAILABLE	"LDAP server is unavailable",
    821	LDAP_UNWILL_TO_PERFORM	"LDAP server is unwilling to perform",
    822	LDAP_LOOP_DETECT	"Loop detected by LDAP",
    832	LDAP_NAMING_VIOLATION	"LDAP naming violation",
    833	LDAP_OBJ_CLS_VIOLATION	"LDAP object class violation",
    834	LDAP_NOT_ALLOW_NONLEAF	"LDAP operation not allowed on non-leaf",
    835	LDAP_NOT_ALLOW_ON_RDN	"LDAP operation not allowed on RDN",
    836	LDAP_ALREADY_EXISTS	"Already exists (LDAP)",
    837	LDAP_NO_OBJ_CLASS_MODS	"Cannot modify LDAP object class",
    838	LDAP_RESULTS_TOO_LARGE	"LDAP results too large",
    839	LDAP_AFFECTS_MULT_DSAS	"LDAP operation affects multiple DSAs",
    844	LDAP_VLV		"Virtual LDAP list view error",
    848	LDAP_OTHER		"Other LDAP error",
    881	LDAP_CUP_RESOURCE_LIMIT	"Resources exhausted in LCUP",
    882	LDAP_CUP_SEC_VIOLATION	"Security violation in LCUP",
    883	LDAP_CUP_INV_DATA	"Invalid data in LCUP",
    884	LDAP_CUP_UNSUP_SCHEME	"Unsupported scheme in LCUP",
    885	LDAP_CUP_RELOAD		"Reload required in LCUP",
    886	LDAP_CANCELLED		"LDAP cancelled",
    887	LDAP_NO_SUCH_OPERATION	"No LDAP operation to cancel",
    888	LDAP_TOO_LATE		"Too late to cancel LDAP",
    889	LDAP_CANNOT_CANCEL	"Cannot cancel LDAP",
    890	LDAP_ASSERTION_FAILED	"LDAP assertion failed",
    891	LDAP_PROX_AUTH_DENIED	"Proxied authorization denied by LDAP",
    1024	USER_1			"User defined error code 1",
    1025	USER_2			"User defined error code 2",
    1026	USER_3			"User defined error code 3",
    1027	USER_4			"User defined error code 4",
    1028	USER_5			"User defined error code 5",
    1029	USER_6			"User defined error code 6",
    1030	USER_7			"User defined error code 7",
    1031	USER_8			"User defined error code 8",
    1032	USER_9			"User defined error code 9",
    1033	USER_10			"User defined error code 10",
    1034	USER_11			"User defined error code 11",
    1035	USER_12			"User defined error code 12",
    1036	USER_13			"User defined error code 13",
    1037	USER_14			"User defined error code 14",
    1038	USER_15			"User defined error code 15",
    1039	USER_16			"User defined error code 16",
    1500	SQL_OK		"SQL success",
    1501	SQL_ERROR	"SQL error",
    1502	SQL_INTERNAL	"Internal logic error in SQL library",
    1503	SQL_PERM	"Access permission denied (SQL)",
    1504	SQL_ABORT	"SQL abort was requested",
    1505	SQL_BUSY	"SQL database file is locked",
    1506	SQL_LOCKED	"An SQL table in the database is locked",
    1507	SQL_NOMEM	"SQL library ran out of core",
    1508	SQL_READONLY	"Attempt to write a readonly SQL database",
    1509	SQL_INTERRUPT	"SQL operation terminated by interrupt",
    1510	SQL_IOERR	"I/O error during SQL operation",
    1511	SQL_CORRUPT	"SQL database disk image is malformed",
    1512	SQL_NOTFOUND	"Unknown opcode in SQL file control",
    1513	SQL_FULL	"Insertion failed because SQL database is full",
    1514	SQL_CANTOPEN	"Unable to open the SQL database file",
    1515	SQL_PROTOCOL	"SQL database lock protocol error",
    1516	SQL_EMPTY	"(internal SQL code: empty)",
    1517	SQL_SCHEMA	"SQL database schema changed",
    1518	SQL_TOOBIG	"String or blob exceeds size limit (SQL)",
    1519	SQL_CONSTRAINT	"SQL abort due to constraint violation",
    1520	SQL_MISMATCH	"Data type mismatch (SQL)",
    1521	SQL_MISUSE	"SQL library used incorrectly",
    1522	SQL_NOLFS	"SQL library uses unsupported OS features",
    1523	SQL_AUTH	"Authorization denied (SQL)",
    1524	SQL_FORMAT	"(unused SQL code: format)",
    1525	SQL_RANGE	"SQL bind parameter out of range",
    1526	SQL_NOTADB	"File opened that is not an SQL database file",
    1527	SQL_NOTICE	"Notifications from SQL logger",
    1528	SQL_WARNING	"Warnings from SQL logger",
    1600	SQL_ROW		"SQL has another row ready",
    1601	SQL_DONE	"SQL has finished executing",
    16381	MISSING_ERRNO		"System error w/o errno",
    16382	UNKNOWN_ERRNO		"Unknown system error",
    16383	EOF			"End of file",
}
